### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by willirath** [willirath/ABCDE-demo#2]
- [ ] Add minimal example loading the LLC4320 data. (See <https://github.com/rabernat/poseidon-bot/blob/master/llcbot.ipynb> for the relevant catalog entries.)
- [ ] Add `fpzip` to the image. Make sure to also have it in the worker image.
- [ ] Adapt Readme to make sure to only provide a binder link for the cloud provider which has the LLC4320 data (Google, I think).
- [ ] Demo cases
  - [ ] A completely water-filled box in the open ocean (x, y, t). _(This should look fine and give a good impression about what's possible with lossy compression.)_
    - Calculate EKE (`eddy kinetic energy = 0.5 * (var[u] + var[v])`) for the uncompressed data, show map.
    - Compress / decompress lossy (different rates) and calculate / compare EKE from lossy decompressed data.
  - [ ] Repeat EKE from uncompressed / lossy data for a box with islands / coastline. _(This will show problems that can be solved with learning / training how to handle masked areas and might show different mitigation ideas.)_
    - Show problems for plot across full box. Errors will be present near coasts.
    - Select a section / line that crosses the coast at some point and show how the error is reduced with increasing distance from coast.
    -  Mitigation 1: Repeat same section but select sequence of data sent to `fpzip` that does not include masked data. _(For the demo, a hand-picked path works fine. For production across huge datasets, we'll need ML to learn how to pick paths automatically.)_
    - Mitigation 2: Adapt algorithm to change the stencil size near masked data. _(Not sure we can easily do this based on `fpzip`?)_
    - Mitigation 3: Fill in masked data in a way that allows for only sending smooth data to fpzip. Extrapolating into land-covered regions worked fine when I played with this in December. _(Not an ML appraoch, however. ?)
